Genode: Do not use DCHECK_LE
When DCHECK_LE is used in terms with the constexpr specifier, this
causes an error like this:

error: call to non-constexpr function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const char*) [with _Traits = std::char_traits<char>]’