Genode: Do not use DCHECK_NE
When DCHECK_NE is used in terms with the constexpr specifier, this causes an
error like this:

  error: call to non-constexpr function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const char*) [with _Traits = std::char_traits<char>]’